spring.datasource.url=jdbc:mysql://localhost:3306/ccis_db
spring.datasource.username=ccis_user
spring.datasource.password=ccispwertug_db
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver